outline:main.o adddata.o print.o count.o readdfile.o savedfile.o
	cc main.o adddata.o print.o count.o readdfile.o savedfile.o -o outfile
main.o:main.c
	cc -C main.c
adddata.o:adddata.c
	cc -C adddata.c
print.o:print.c
	cc -C print.c
count.o:count.c
	cc -C count.c
readdfile.o:readdfile.c
	cc -C readdfile.c
savedfile.o:savedfile.c
	cc -C savedfile.c

